### ISSUE TITLE
Italic style does not work in MS Office Word

### ISSUE THREAD

**Issue by babca** [cyrealtype/Lora-Cyrillic#1]
Hi there! I downloaded the latest version from github, but it seems the font does not work in Office 2013. The Word applies faux italic style when Italic button is on. It seems to work fine on OS X.

**Comment by davelab6** [comment]
@alexeiva check the macStyle and fsSelection

**Comment by alexeiva** [comment]
fixe now

<img width="685" alt="screen shot 2016-07-16 at 00 53 57" src="https://cloud.githubusercontent.com/assets/16634089/16892904/ee6f8c50-4af1-11e6-91b9-30a53e7dff1a.png">
