### ISSUE TITLE
Blurry text after update

### ISSUE THREAD

**Issue by alexeiva** [cyrealtype/Lora-Cyrillic#11]
A user reported an issue with text rendering:

> In the last days I've seen the Lora font have been changed. Now have more "body". I guess that is an update. But in the post body text, the font looks blurry. So, Before the update the font was very clear. After update, the font with the small size is blurried. 

> I use Firefox and Chrome (here is much more evident). My OS is Windows 8. But I use Mac and Vista, and I saw the same. I don`t think that this is an issue. But, I prefer the last version for my web. Congrats for the work.

![0](https://cloud.githubusercontent.com/assets/16634089/22262245/32ba7f88-e281-11e6-8bf6-35c31e5ebb1e.jpeg)

**Comment by alexeiva** [comment]
@m4rc1e Looks like a ttfautohint issue. Could you investigate this? /cc @davelab6

**Comment by m4rc1e** [comment]
Interesting,

Which platform was that screenshot taken on?

**Comment by alexeiva** [comment]
Windows 8, Chrome(more evident) and Firefox.

User reported that the updated font is not only blurry, but more grayish. 
> I use blogger, and google fonts, of course. Before all the was black; after is grey.

and was kind to share more photos:

![0-2](https://cloud.githubusercontent.com/assets/16634089/22263415/761e12cc-e285-11e6-8f28-7da67ccc2a14.jpeg)
![0-1](https://cloud.githubusercontent.com/assets/16634089/22263570/f40d676e-e285-11e6-9837-38c47fb9237a.jpeg)

**Comment by alexeiva** [comment]
Further inspection did not confirm any ttfautohinting issues. Closing since this is third-party behavior, outside of our influence.

**Comment by davelab6** [comment]
Was Lora hand hinted before?

Can Marc reproduce the regression?

**Comment by alexeiva** [comment]
Actually you are right, Dave. Lora was manually hinted in 2011. 
2013 Extended Latin and Cyrillic support was added using Glyphs App, and ttfautohinting was used instead of the previous manual hints. 

So the recent update supercedes the 2013 ttfautohinted version, unless the 2013 version has not been pushed to the servers? If not than a change from the 2011-version with manual hints to ttfautohinted 2016 is likely the cause.  

@m4rc1e here are the 2011 and 2013 source files for comparison:

2011, Manually hinted VBFs:
https://github.com/cyrealtype/Lora-Cyrillic/tree/363a8bef781351210149a9a437449748d853181f/src/TTF

2011 TTFs:
https://github.com/cyrealtype/Lora-Cyrillic/tree/363a8bef781351210149a9a437449748d853181f

Glyphs App sources for 2013::
https://github.com/cyrealtype/Lora-Cyrillic/tree/4e9f3e5a744d366ac87e9acbf076f62637cdb88c/src

**Comment by davelab6** [comment]
Cool, yes I expect the 2011 version was still in place. 

I'll ask Micah to quote for manually redoing it. 

Are sure this version is rock solid and won't need to be updated substantially for another 6 years? :D

**Comment by alexeiva** [comment]
Then it makes sense to make all glyphs compatible before hinting. In case we want to make a variable Lora in the future.

**Comment by davelab6** [comment]
With the latest update completed today, I will queue this up for @laerm

**Comment by davelab6** [comment]
Sorry I meant @laerm0

**Comment by davelab6** [comment]
> make all glyphs compatible before hinting

I guess this comes after Nunito; is it possible to do it this year?

**Comment by alexeiva** [comment]
Yes, I think so. At the moment 323 incompatible glyphs.

<img width="1199" alt="screen shot 2017-11-05 at 1 48 31 pm" src="https://user-images.githubusercontent.com/16634089/32503047-ad1ba3dc-c3f5-11e7-9775-7b3eddc46805.png">

**Comment by laerm0** [comment]
Hey @alexeiva, I looked through the files you linked in your post from 15 Feb and I can't find anything manually hinted: there are no TTFs with source and the files from 2011 don't appear to have any VFBs. 

![screen region 2017-11-20 at 15 18 15](https://user-images.githubusercontent.com/10780161/33039477-1483114e-ce06-11e7-9fc5-ffe5d7dd913c.png)

Are we sure these were manually hinted at some point?

**Comment by alexeiva** [comment]
I've uploaded them in the `old` folder here: https://github.com/cyrealtype/Lora-Cyrillic/tree/master/old/v1.000/sources

**Comment by laerm0** [comment]
Great, thanks @alexeiva!

**Comment by laerm0** [comment]
So Lora here was manually hinted in FontLab, which means that it's not ttfautohint, and also means that specifically fixing the issue reported here is a bit...veiled. I dunno about you, but it always seems like there's a degree of separation between TT hinting in FL and what you get on the screen, especially with modern renderers. So, considering that @alexeiva is going to update this font for further future-proofing, I think we should just ttfautohint this for now and revisit when the font is prepped for perhaps becoming variable.

Another possibility for me here, if we want to speed that project along, is I can go through and make the glyphs compatible in Glyphs for you, @alexeiva. What do you think, @davelab6?

**Comment by alexeiva** [comment]
Not to worry, the compatibility fix was scheduled for me, I'm working on it [here](https://github.com/cyrealtype/Lora-Cyrillic/tree/variable). There's a number of design issues that need to be revised along the way, for example Ђ requires a bracket layer:
<img width="346" alt="screen shot 2017-12-19 at 10 32 28 pm" src="https://user-images.githubusercontent.com/16634089/34172806-ae8bdae2-e50c-11e7-9d06-1e270341c9d0.png">

I agree that ttfautohint is a viable option at this stage.

**Comment by alexeiva** [comment]
All glyphs are now compatible in Lora. I will be ready to hand this off for hinting after some metrics and perhaps some minor design refinements.
