### ISSUE TITLE
Add Eng glyph

### ISSUE THREAD

**Issue by Kesantielu** [cyrealtype/Lora-Cyrillic#12]
Unicode | Glyph | Description
-- | -- | --
U+014A | Ŋ | Latin Capital Letter Eng
U+014B | ŋ | Latin Small Letter Eng

**Comment by alexeiva** [comment]
Thanks @Kesantielu. This will be done under the next milesone, charset expansion to GF Latin Plus.

**Comment by davelab6** [comment]
@alexeiva was this done?

**Comment by davelab6** [comment]
Ah yes, I see it in https://github.com/cyrealtype/Lora-Cyrillic/commit/3615da408ac8d9d1a2c29f8f7b649dcc09c8814a and https://github.com/cyrealtype/Lora-Cyrillic/commit/3a55c84b411f6d5eb725612aba69b22da9f8231f
