### ISSUE TITLE
2 cyrillic glyphs have changed 

### ISSUE THREAD

**Issue by m4rc1e** [cyrealtype/Lora-Cyrillic#17]
![lora-bad-cyrl](https://user-images.githubusercontent.com/7525512/32144232-ac536858-bcad-11e7-8898-46570a4d661d.gif)

New fonts have non italicized forms. Was this intentional?

If it needs changing, please merge #16 first, then fix it.

**Comment by alexeiva** [comment]
This was an intentional mistake. I fixed the Roman schwa intentionally, but now see that duplicating this in Italic was a mistake.

**Comment by alexeiva** [comment]
Here are the updated glyphs. /schwa and /schwa-cy have different designs. This is a proper solution for such a serif design.

_Left: schwa. Right: schwa-cy_
<img width="370" alt="screen shot 2017-10-30 at 12 46 25 pm" src="https://user-images.githubusercontent.com/16634089/32163767-a09d3b2c-bd72-11e7-8b7a-c2c4c1a4126d.png">
<img width="506" alt="screen shot 2017-10-30 at 12 46 43 pm" src="https://user-images.githubusercontent.com/16634089/32163769-a10562f6-bd72-11e7-95c7-c4ca73a50a00.png">

**Comment by m4rc1e** [comment]
Beautiful! thank you!

**Comment by alexeiva** [comment]
@m4rc1e Fully resolved now, and rebased onto master.
