### ISSUE TITLE
Variable font version

### ISSUE THREAD

**Issue by o-t-w** [cyrealtype/Lora-Cyrillic#23]
Are there any plans to release a variable version of this font?

**Comment by alexeiva** [comment]
It is in development in this branch https://github.com/cyrealtype/Lora-Cyrillic/tree/variable

**Comment by alexeiva** [comment]
The 2.200 variable font pre-release is now available for testing https://github.com/cyrealtype/Lora-Cyrillic/releases/tag/v2.200

**Comment by o-t-w** [comment]
Very exciting @alexeiva 
I'm using Lora on a large website and would love to start using this version as soon as its ready! 
I've been trying out the pre-release. At the heaviest weights the top of the lowercase t looks a bit wrong. Other than that it looks really good.

**Comment by o-t-w** [comment]
I've been looking through the letterforms of the italic today. The uppercase A definitely needs some work. The lowercase s could use a second look at lighter weights. 👍

**Comment by o-t-w** [comment]
I'm doing a presentation at the Financial Times early next month about variable fonts and would love to use Lora as an example. Do you have any timeframe estimate on the font exiting its beta test phase?

**Comment by o-t-w** [comment]
I tried to compress the fonts into woff2 with a google tool called woff2 (which I've tried with a lot of variable fonts and works well). I got the following error, but only for the italic font.
```
Processing Lora-var-italic.tff => Lora-var-italic.woff2
Parsing of the input font failed.
Compression failed.
```

**Comment by alexeiva** [comment]
Stable version is out https://github.com/cyrealtype/Lora-Cyrillic/releases/tag/v2.202.

> Processing Lora-var-italic.tff => Lora-var-italic.woff2
> Parsing of the input font failed.
> Compression failed.

I suppose it will work with the new files. If not, provide me a link to the tool. The font name field has been updated to include 'Italic', which probably caused the issue.

**Comment by o-t-w** [comment]
The new files work perfectly 😊
