### ISSUE TITLE
Variable font CSS integration

### ISSUE THREAD

**Issue by o-t-w** [cyrealtype/Lora-Cyrillic#25]
Safari is the first browser to have fully implemented variable fonts. In that browser using the CSS property `font-weight` works to control the "wght" axis of any variable font. I've tried it with a few different fonts (Source Sans Pro, for instance). Unfortunately Lora doesn't work in conjunction with the CSS font-weight property, it only works with `font-variation-settings`. This is expected in Chrome, which hasn't fully supported variable font integration with CSS yet. However, it should work in Safari but doesn't.

**Comment by alexeiva** [comment]
this is fixed in https://github.com/cyrealtype/Lora-Cyrillic/releases/tag/v2.210
