### ISSUE TITLE
Error in internal family name in Variable Lora Italic

### ISSUE THREAD

**Issue by demoy** [cyrealtype/Lora-Cyrillic#30]
In several places Variable Lora Italic is named as a different font-family (and as regular style): Applications under linux are resorting to using fake italic in its place. 

![screenshot_20180830_152616](https://user-images.githubusercontent.com/2396524/44877868-ebf4cd00-ac6a-11e8-8a9b-8ec06c6560ab.png)

![screenshot_20180830_152546](https://user-images.githubusercontent.com/2396524/44877869-ebf4cd00-ac6a-11e8-9a52-da5966fee860.png)

Family Name should be "Lora" instead of "Lora Italic".

![screenshot_20180830_155245](https://user-images.githubusercontent.com/2396524/44878662-15165d00-ac6d-11e8-879b-9952a56f24df.png)

Style Map should be "Italic" instead of "Regular".

**Comment by alexeiva** [comment]
fixed in https://github.com/cyrealtype/Lora-Cyrillic/releases/tag/v2.210
