### ISSUE TITLE
Weight Axis variable font

### ISSUE THREAD

**Issue by pichotta** [cyrealtype/Lora-Cyrillic#31]
@alexeiva 
Hi Alexie,

As you are familiar we would like to resume and resolve any remaining issues related to a variable font weight axis for **Lora**. 

I see from the commits that there are some Glyphs sources used to make a VF.ttf in the branch "variable".  Are these the latest sources?  Thank you!

_alexeiva fixed variable font issues
Latest commit 5e5246b on Jan 18, 2018
	variable	fixed variable font issues	2 years ago
	Lora-Italic.glyphs	fixed variable font issues	2 years ago
	Lora.glyphs	fixed variable font issues	2 years ago_

Hello Olga,

The Google fonts team would love to see a variable fonts version of ‘Lora'. They have commissioned us @TypeNetwork to work on upgrading a number of font projects to be variable fonts with a single weight axis.

In order to achieve the highest quality and most efficient long term results we will be converting the source data from Glyphs to UFO. The new source data will be generated in the RoboFont environment using fontmake and ttfautohint. There has been progress on tools to make an easy path to move between the Glyphs and Robofont environment.

During the process we will be looking to improve any errors while preserving how the font appears and renders on different platforms.

We have started by making a fork off of this git repository. The upgrade will be completed for you in the near future. When the proposed final font is approved by Google they will accept a pull request.

We hope this answers some of your questions about the process. Please let us know if you have any additional comments.

Best Regards,

Jill Pichotta
Vice President
Type Network
pichotta@typenetwork.com

**Comment by alexeiva** [comment]
Hello
Yes, those are the latest sources
