### ISSUE TITLE
U+1E25 (ḥ) not handled properly

### ISSUE THREAD

**Issue by bstpeg** [cyrealtype/Lora-Cyrillic#34]
Screenshot from Google Fonts demonstrating the issue is attached. The dot that is supposed to be below the h is below the following letter instead.

The same issue exists with the capital-H version of this letter (U+1E24).

I looked at the font file and I see this character isn't defined. For some reason, other fonts I've looked at do handle it properly even though the character isn't defined in their font file either.

I'm not familiar with fonts, so I don't know what right fix would be - I assume defining the character in the font would be the best.

<img width="256" alt="Screen Shot 2020-05-04 at 10 39 17 AM" src="https://user-images.githubusercontent.com/4523223/80978375-f5e1b280-8df3-11ea-826d-ff017353c580.png">

**Comment by alexeiva** [comment]
This character isn't part of the glyph set, but is generated on the fly using `h` and `dotbelow` components. I've added a bottom anchor to remedy this in the static font sources
