### ISSUE TITLE
Backtick (`) is TOFU 

### ISSUE THREAD

**Issue by davelab6** [cyrealtype/Lora-Cyrillic#36]
<img width="848" alt="Screen Shot 2020-07-08 at 2 28 16 PM" src="https://user-images.githubusercontent.com/261579/86956589-54dee300-c127-11ea-854b-f1166c3eb946.png">

**Comment by pakpenyo** [comment]
+1

**Comment by alexeiva** [comment]
This is resolved 
`U+0060 GRAVE ACCENT`

<img width="372" alt="Screenshot 2022-01-20 at 12 32 47" src="https://user-images.githubusercontent.com/16634089/150312051-552011f6-da23-44be-8ca6-64c231c4f299.png">
