### ISSUE TITLE
The right sidebearing of 'j' is too tight.

### ISSUE THREAD

**Issue by nasir-udin** [cyrealtype/Lora-Cyrillic#37]
It seems the right sidebearing of 'j' is too tight. (for non-italic styles)

![Screen Shot 2020-08-21 at 14 14 38](https://user-images.githubusercontent.com/61658536/90858662-3c661780-e3b9-11ea-99fb-d9cf0f6d76d5.png)

**Comment by moosotc** [comment]
This thing irks me too.
cf
https://github.com/moosotc/llpp/commit/470024861a54b907e0d428a091673610060c414f#diff-9c32429c292637fdf6cb659cd0ba247b03ac4980727fca1df0636eca84751ea2
and
https://github.com/moosotc/snippets/commit/553d969aea49d7297f19f88f31c01ae3e029540c

**Comment by bungeman** [comment]
I was just reading https://entropymine.wordpress.com/2021/04/28/the-two-envelopes-problem/ which uses Lora from Google Fonts and found the space between of the 'j' and 'e' in 'subject' to be so jarring that I went searching and found this issue.
