### ISSUE TITLE
Vietnamese accents in Italic sources

### ISSUE THREAD

**Issue by m4rc1e** [cyrealtype/Lora-Cyrillic#5]
Hey folks,

![screen shot 2016-09-21 at 12 50 48](https://cloud.githubusercontent.com/assets/7525512/18708237/2dae657a-7ffa-11e6-979e-5ef5651d7367.png)

**Comment by crystaltype** [comment]
Oh sorry, fixed that it my newest pull request

**Comment by alexeiva** [comment]
@m4rc1e  

Thanks Marc, 
Your eye is golden

fixed in ba7b7bd863d14577ef89c72994472e2044b81447
