### ISSUE TITLE
joined letters issues with the f, i and l

### ISSUE THREAD

**Issue by athuthu** [cyrealtype/Lora-Cyrillic#53]
Hi,

I saw a video on inclusive typography and there is an issue with Lora about joined letters.
To improve the accessibility and readability, it is better to avoid ligature (ie. create uncommon character / screen readers can struggle to read the typeface) ([part of the video](https://youtu.be/ha768Ih6J8M?t=1312))

Especially with the f, i and l. What is strange is that it doesn't display the same way on figma:
<img width="756" alt="image" src="https://user-images.githubusercontent.com/101270747/157466483-9c506947-ccb8-4c9c-90ce-f81aa3daeaea.png">

**Comment by alexeiva** [comment]
Looks like Figma has ligatures turned off by default. 

The ligatures (liga) feature can also be turned off in other apps like Illustrator of via css.
