### ISSUE TITLE
Ț and Ă small-caps on iPhone 13 Safari shows "Â " instead

### ISSUE THREAD

**Issue by bogdandragomir** [cyrealtype/Lora-Cyrillic#54]
Hi,

"Ț" and "Ă" characters when in small-caps on Safari (iPhone 13) shows "Â " instead.
Could this be a font related problem or is an error in iOS Safari?
I just sent a report to Safari team also.

This is the page where you can check:
https://www.imuno-medica.ro/lab/Infectii-severe-sau-recurente-af19.htm

Thanks,
Bogdan

![1](https://user-images.githubusercontent.com/2846921/159810265-69eab6c6-b02f-4063-bb3e-f2d60e534b60.png)

**Comment by alexeiva** [comment]
There are no small caps in Lora. What you are seeing is fake small caps generated by Safari.

Have you tried Small Caps from lower case letter:  ```ă ț``` ?


I could not replicate this issue in Chrome:
<img width="189" alt="Screenshot 2022-04-08 at 14 50 46" src="https://user-images.githubusercontent.com/16634089/162430209-3e3a9611-f138-4754-8df6-64601e471c1f.png">

Font Testing page:
http://cyreal.org/Font-Testing-Page/

**Comment by alexeiva** [comment]
This is a Safari bug:




<img width="1173" alt="Screenshot 2022-04-08 at 14 57 08" src="https://user-images.githubusercontent.com/16634089/162431036-19919b05-1df8-4cf2-a790-59855df1a8d9.png">
left — Safari Version 15.1 (16612.2.9.1.30, 16612). Right — Chrome. 

Mac OS 11.6 Bug Sur.

**Comment by bogdandragomir** [comment]
> Have you tried Small Caps from lower case letter: `ă ț` ?

The text is in lower case in source.
