### ISSUE TITLE
Spacing around backtick / unwanted accents

### ISSUE THREAD

**Issue by benrbray** [cyrealtype/Lora-Cyrillic#55]
Thank you for this beautiful font!  I'm using it as one of the font options for a math-focused WYSIWYG markdown editor.  Accordingly it is common to include backticks `\`` as part of markdown syntax.  However, I've been experiencing mysterious accent characters appearing while using the Lora font, which don't appear when using any other fonts:

![image](https://user-images.githubusercontent.com/221963/162753732-60af651a-4fc3-45cc-b549-fab5a0f7f122.png)

![image](https://user-images.githubusercontent.com/221963/162754218-0be09d50-ec94-4698-8f3c-b7c3dd8e4791.png)

As you can see, the raw text is just `` mysterious `accent` ``, with no accented characters.  Can you think of a reason why Lora would cause this issue?  Is there any way to fix it?  I've already tried `font-variant-ligatures: none`.

Notably, I cannot reproduce the issue on Google fonts:

![image](https://user-images.githubusercontent.com/221963/162754457-3bc05b23-9fc0-4b94-92dd-ae436d77008d.png)

**Comment by alexeiva** [comment]
Grave accent combined with Latin `a` produces `aacute` thanks to glyphs composition

U+0060 GRAVE ACCENT

you need to disable `ccmp` feature, not ligatures
https://helpx.adobe.com/fonts/using/open-type-syntax.html#ccmp

**Comment by benrbray** [comment]
Thanks for the reply.  Do you know the correct way to disable `ccmp`?  I've tried both of the below with no luck.  Any alternatives to this?

```css
font-feature-settings: "ccmp" off;
font-feature-settings: "ccmp" 0;
```

**Comment by thlinard** [comment]
@benrbray 
Seems your editor replaces `U+0060 GRAVE ACCENT` by `U+0300 COMBINING GRAVE ACCENT`.

**Comment by alexeiva** [comment]
Actually `grave` has an unnecessary `top` anchor that fixates to base glyphs. That was my oversight in from an older version. So removing this anchor should solve the issue. 

![Screenshot 2022-04-22 at 14 22 34](https://user-images.githubusercontent.com/16634089/164705412-85679101-4023-4dcd-a391-aad71213645b.png)

**Comment by alexeiva** [comment]
@benrbray Let me know if this version works for you.
[Lora-v3.003.zip](https://github.com/cyrealtype/Lora-Cyrillic/files/8540568/Lora-v3.003.zip)

**Comment by benrbray** [comment]
It works!! Thank you very much!
