### ISSUE TITLE
The period under the letter e is not centered

### ISSUE THREAD

**Issue by ftcminh** [cyrealtype/Lora-Cyrillic#56]
Same issue with capital E.

![not_centered](https://user-images.githubusercontent.com/3332262/164562088-7a3c6867-c65a-4ffc-a449-70fe9789cef2.png)

**Comment by alexeiva** [comment]
Thanks for spotting this. Updated in the sources. Stay updated for new a release with this fix. 

![Screenshot 2022-04-22 at 14 37 20](https://user-images.githubusercontent.com/16634089/164707469-4b7f7382-bbd4-4ef7-900d-90b0e1d34084.png)


![Screenshot 2022-04-22 at 14 37 01](https://user-images.githubusercontent.com/16634089/164707482-5238681d-5305-4ec8-8c1d-185e85b8f9cf.png)

**Comment by alexeiva** [comment]
fixed in https://github.com/cyrealtype/Lora-Cyrillic/releases/tag/v3.003

**Comment by ftcminh** [comment]
Is it possible to apply the fix on Google Fonts, Google Docs, Google Sheets, Google Slides as well? Thanks.

**Comment by alexeiva** [comment]
> Is it possible to apply the fix on Google Fonts, Google Docs, Google Sheets, Google Slides as well? Thanks.

@thlinard @davelab6 can you add this to the updates list?

**Comment by thlinard** [comment]
Hi @alexeiva 

I'm a simple user here, I believe the "Update Font" template on https://github.com/google/fonts/issues/new/choose is the way to go, but @RosaWagner can confirm that for you.
