### ISSUE TITLE
Use same width for digits?

### ISSUE THREAD

**Issue by Hatshepsut71** [cyrealtype/Lora-Cyrillic#60]
Hello,
I'm using Lora font in my forum.
I noticed that digits have different width. When numbers are displayed in table or vertical list, the columns with numbers are not adjusted by digit groups.
![2023-01-04](https://user-images.githubusercontent.com/68983397/210484666-6eb25946-a3cc-4e2f-b427-caa7e403dc6a.png)

I would ask you to make all digits to use same width, in the future versions of Lora font.

**Comment by alexeiva** [comment]
Lora has an additional tabular figures set. 
<img width="590" alt="Screen Shot 2023-01-06 at 13 00 58" src="https://user-images.githubusercontent.com/16634089/210948249-c072014e-92a0-4ac1-b570-b61237a10c70.png">


You can turn it on in css via: 
```font-variant-numeric: tabular-nums;```

More info:
https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric

**Comment by alexeiva** [comment]
Hello
I've just replied to you on github.
https://github.com/cyrealtype/Lora-Cyrillic/issues/60

On Wed, Jan 4, 2023 at 10:29 AM Radoslav Tinchev ***@***.***>
wrote:

> Hello,
> I'm using Lora font in my forum.
> I noticed that digits have different width. When numbers are displayed in
> table or vertical list, the columns with numbers are not adjusted by digit
> groups.
> [image: 2023-01-04]
> <https://user-images.githubusercontent.com/68983397/210484666-6eb25946-a3cc-4e2f-b427-caa7e403dc6a.png>
>
> I would ask you to make all digits to use same width, in the future
> versions of Lora font.
>

Font update requests require additional funding.

**Comment by Hatshepsut71** [comment]
Thanks, problem solved, I don't knew for this CSS option.
