### ISSUE TITLE
Issue with % glyph

### ISSUE THREAD

**Issue by Hatshepsut71** [cyrealtype/Lora-Cyrillic#62]
Hello,
I'm using Lora font on my forum, with "font-variant-numeric: tabular-nums;" option enabled.
I have noticed that % glyph is stickied to left/right characters in text, without any margins:

![2023-01-27 (1)](https://user-images.githubusercontent.com/68983397/215020311-a049b350-562f-4d90-b536-929fb787971a.png)

And that's normal behavior, if "font-variant-numeric: tabular-nums;" is not enabled:

![2023-01-27](https://user-images.githubusercontent.com/68983397/215020499-7bfd6b15-9c55-45f5-bbb3-4385a2c08bc9.png)

(The screenshots are from my test forum)

**Comment by alexeiva** [comment]
I see the problem in tabular `%`, thank you for reporting
